### ISSUE TITLE
Citation for "mountain of engagement"?

### ISSUE THREAD

**Issue by ewallace** [swinterbourne/riboviz-work#11]
See https://twitter.com/MalvikaSharan/status/1437733414292049922

**Comment by swinterbourne** [comment]
To confirm before I insert this citation: it is the "Mini Talks/Videos about Open Science from OLS-3 Cohort" which includes the video "Explore the Mountain of Engagement in 10 Minutes" to be cited as:

Malvika Sharan; Hao Ye; Yo Yehudi; Emmy Tsang; Carlos Martinez; Helena Rasche; Esther Plomp; Andre Maia Chagas; Iratxe Puebla; Lenny Teytelman; Georgia Aitkenhead; Batool Almarzouq; Suzanne lwai; Otis Smith; Sarah Markham; Emma Anne Harris; Alex Holinski; Neil P. Chue Hong; David Selassie Opoku;  Zulidyana Rusnalasari; Nelsy Mtsweni; Rowland Mosbergen and Anelda van der Walt. (2021, July 5). OLS-3 Cohort Talks and Transcripts (v1.0). Zenodo. https://doi.org/10.5281/zenodo.5071349

**Comment by ewallace** [comment]
Yes, that looks right!

**Comment by ewallace** [comment]
Added to Further Reading #16, can close this issue.
