### ISSUE TITLE
Organize the "top takeaways"

### ISSUE THREAD

**Issue by ewallace** [swinterbourne/riboviz-work#13]
I wonder if the "top takeaways" sections read better coming at the end of each section, or collected in a box at the end? Let's discuss.

I think it would be better if there was more similarity in tone & length between them too. @FlicAnderson 's draft has them on the longer side, mine on the shorter side. Should I add to mine? What do we all think?

**Comment by FlicAnderson** [comment]
Undergrad tips: 
* make lengths more similar, reduce first point. @3mma-mack I think planned to work on this. 
* combine or put next to each other the point about 'learning resources' documentation, and 'documenting your work', as these are fairly similar and work together.
* perhaps could move "open-science is like a group project" bullet point to the end of these tips for better impact! :)

Day-to-day-supervisor tips: @FlicAnderson 
* Put these tips next to each other - tools early/often, research environment inclusion early/often - as they're fairly similar & this will reinforce them
* Reduce wordage in each point.  - make more bullet-point-y to better match other tips

PI tips: @ewallace 
* re: open science benefits tip: mention names on papers/documentation contributions/assistance with tasks - "project students have both time and motivation to contribute"
* re: plan path from novice to expert: add sentence mentioning why: ie manageable achievable tasks gain confidence & skills. Avoids overwhelm. Helps to reduce 'Unknown unknowns'!  
* Perhaps add a point about the benefits of offering similar projects in subsequent years, as you can build on previous work, learnings & experience.

**Comment by FlicAnderson** [comment]
I've made my edits in `takeaways-13-flic` branch & updated the .docx too (as of commit a898c4c2c1) . I'll pull request these separately to merge with main since they're ready now.

**Comment by 3mma-mack** [comment]
I have shortened the first undergrad Top Tips tip, and have merged this change into main

**Comment by ewallace** [comment]
I think we have discussed and addressed this sufficiently.
