### ISSUE TITLE
Snappier title?

### ISSUE THREAD

**Issue by ewallace** [swinterbourne/riboviz-work#14]
What title do we really want to have?

- Open science in undergraduate projects
- How open science empowers student research projects
- How everyone can benefit from taking an open science approach to student research projects

Or better???

**Comment by 3mma-mack** [comment]
The benefits of an open science approach in undergraduate research projects?

**Comment by FlicAnderson** [comment]
@3mma-mack I like that one!

**Comment by ewallace** [comment]
I also like that one. I do think it applies to MSc research projects as well as UG though, so could we go for the more general:
"The benefits of an open science approach in undergraduate research projects?"

**Comment by FlicAnderson** [comment]
Think this is good to close now since it's merged.
