### ISSUE TITLE
Pandoc conversion to word + markdown header

### ISSUE THREAD

**Issue by ewallace** [swinterbourne/riboviz-work#19]
To get comments from others, and to submit to The Biochemist, we will probably need to put in word format (yes, I know).

That will be helped by:
* markdown header with key info including authors
* using pandoc to convert to word directly from the markdown format

We did the same with the riboviz 2 manuscript, but using a pretty complex citation management and template system. Let's keep things much simpler here.

**Comment by ewallace** [comment]
@FlicAnderson might you have time for the header / pandoc this week? My laptop with the pandoc installation is still down.

**Comment by FlicAnderson** [comment]
I've created branch `doc-conversion-19`, included a yaml header with author information (same order used as that in the README.md file) and used `pandoc` to generate a .docx word format. 

Generating .docx from .md was done on my Ubuntu machine by running the following from the terminal (in the `riboviz-work` repo folder), with the `pandoc` software already installed: 
`pandoc -s open-science-projects.md -o open-science-projects.docx`  

The new file `open-science-projects.docx` was generated :ok_hand:
