### ISSUE TITLE
Introduce git / github

### ISSUE THREAD

**Issue by ewallace** [swinterbourne/riboviz-work#21]
We need a 1-sentence explanation of git/github/issue tickets when it's first brought up in the article, because many readers of the biochemist might be unfamiliar with those.

**Comment by ewallace** [comment]
@3mma-mack agreed to take a pass through and
- make sure we introduce all of git, GitHub, issue tickets
- check that when we use those terms it is never confusing
- if needed, add something to Further Reading

**Comment by 3mma-mack** [comment]
In the introduction, GitHub and issue tickets are mentioned in the introduction,so I have expanded a few sentences to describe these.

`riboviz is an example of open scientific software as all of the code required to run it is accessible on GitHub, a website where software, code and files can be hosted online. Information on errors and developments to riboviz are also documented on Github in the form of issue tickets, which are short forums where users can discuss and provide updates on any problems they run into.`

**Comment by 3mma-mack** [comment]
Added a sentence to introduce Git.

`riboviz is an example of open scientific software as all of the code required to run it is accessible on GitHub, a website where software, code and files can be hosted online. These files can be downloaded, edited and returned to GitHub using Git, which passes information between a local machine and GitHub. Information on errors and developments to riboviz are also documented on GitHub in the form of issue tickets, which are short forums where users can discuss and provide updates on any problems they run into.`

**Comment by 3mma-mack** [comment]
I have merged in the paragraph into main, so closing this issue
