### ISSUE TITLE
Add to hackathon paragraph

### ISSUE THREAD

**Issue by ewallace** [swinterbourne/riboviz-work#3]
> Like a language immersion week, dumped in France and allowed only to speak French, when you know how to say "hello" and "where is the bus stop".

Maybe also something about hackathon showing the social practice of working collaboratively, what does git/github/etc look like?

**Comment by 3mma-mack** [comment]
I have added the following paragraphs.

'Having never worked in a lab before, let alone in a bioinformatics one, this was rather overwhelming. Everyday ended with a meeting, where everyone reported on their day, so there was pressure to learn quickly and be able to share progress. These meetings were like going on an intense language immersion course, and it felt like our brains were melting by the end of each day. There was a steep learning curve,'

'Additionally, we were able to see how a large group could operate efficiently using issue tickets and Git, which at the time were still intimidatingly new to us.'

**Comment by ewallace** [comment]
This looks lovely! I'm closing the issue.
