### ISSUE TITLE
Edit Recommendations

### ISSUE THREAD

**Issue by cjacoby** [swinterbourne/riboviz-work#34]
Hello all! I hope these suggestions aren't too out of nowhere and are useful to you.
Review made at commit `ea08ca8`.

Overall, I think this is looking great 🥇 - the story you're telling is clear, and I like the summaries at the end of each section. And it leaves me excited to hear the next chapter.

## Macro Thoughts
* The biggest structural concern I have with this document in the current read is: as a complete outsider with no knowledge/context, it is not always clear to me who is "talking" during each section. It would be very helpful, since each section is authored by a/multiple different folks, for the "author" of each section to be mentioned somewhere immediately adjacent to the heading for that section.

    One particular case that especially stuck out to me about this was in the subsection `Advice for undergrads selecting their projects`, which suddenly switches from the `we` used in the previous sections (it is essentially clear who `we` is) to `I`, however no context was provided to say who *I* is in this paragraph. I strongly recommend rewriting the paragraph in a way such that is consistent with the rest of `The undergraduate perspective` section.

* What about a concluding section at the end (just before `Further Reading`), where you tie it all together and perhaps suggest how the reader can either do open science, or can help make open science happen in their institution. What specific steps would you do next time? What would a world full of open science look like? 

## Nitpicky stuff
* For my taste, there are too many sentences throughout that start with prepositions. While I'm not against them entirely, I think there are enough that it is affecting readability. 
* The very first sentence of the abstract reads a bit awkwardly to me. I had to read it a few times to parse it right.
* The "style"/"voice" of the headings in the first section is different from the later two; the first is far more informal. This ... might be fine if it's a choice, but tbh it reads to me like someone wrote an outline with silly headers to fill in later and then never renamed them ;)

I hope that was helpful. 🔬

**Comment by ewallace** [comment]
Thank you so much @cjacoby! Super-useful and we will upgrade in response to these.

**Comment by ewallace** [comment]
This is basically addressed by commit 576d046e788985c4382f71fbf09db18f16af956b. Apologies for my incompetent attempt to pull request.

**Comment by ewallace** [comment]
I’m going to close this, having broken out the Concluding section point into a separate issue #37

**Comment by ewallace** [comment]
Even though this issue is closed and edits merged to main, if @3mma-mack and @swinterbourne want to suggest changes to my new subsection headings, please go ahead and address in a separate issue?
