### ISSUE TITLE
Break up long sentences

### ISSUE THREAD

**Issue by ewallace** [swinterbourne/riboviz-work#35]
Upon rereading I noticed some very long sentences, especially in the Day-to-Day section.

@FlicAnderson are you up to having a go editing those into shorter sentences, or would you like me to?

In either case let’s wait until we have resolved #34 and put a pull request into main, because otherwise merge conflicts await.

**Comment by FlicAnderson** [comment]
I'll also have a look at this tomorrow if I have time.

**Comment by FlicAnderson** [comment]
Created branch `break-sentences-35`. Will work on this in there.
