### ISSUE TITLE
Fill in README & repo information 

### ISSUE THREAD

**Issue by FlicAnderson** [swinterbourne/riboviz-work#7]
It'd be good to give some details about what this repository is for, and perhaps add some relevant links to the README (for example to the lab, riboviz, etc).   This makes it more easily discoverable, and helps keep it project-focussed.

Eventually, when the article is published, the readme should contain a link to it :)

**Comment by swinterbourne** [comment]
I have updated the README and added some links - is there anything else I should add/remove @FlicAnderson?

**Comment by ewallace** [comment]
This looks lovely!

* adive -> advice
* add an explicit author list? That's the only thing I picked up on from scanning [how to write a good readme file](https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/)

**Comment by swinterbourne** [comment]
> * add an explicit author list? That's the only thing I picked up on from scanning [how to write a good readme file](https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/)

I added an authors list at the bottom and linked everyone's GitHub profiles - is that ok?

**Comment by ewallace** [comment]
Looks good.
