### ISSUE TITLE
Collect the context for secret projects vs open projects...

### ISSUE THREAD

**Issue by ewallace** [swinterbourne/riboviz-work#8]
* mention that E&S are biotech students
* some "closed" projects at the opposite extreme: confidentiality, contracts, stress
* scare story about IP disclosure on facebook

**Comment by 3mma-mack** [comment]
I have added the paragraph 'Freedom to share information and anxiety' which addresses these points

**Comment by ewallace** [comment]
That paragraph looks great, I'm closing the issue!
