### ISSUE TITLE
Draft immediate supervisor perspective 

### ISSUE THREAD

**Issue by FlicAnderson** [swinterbourne/riboviz-work#9]
Add as section to article within same file, similar to #5.

**Comment by FlicAnderson** [comment]
This is for me to add, covering the day-to-day supervising process re: open science undergrad projects.

**Comment by ewallace** [comment]
Can you put it after the student perspective (takeaways) and before the PI perspective?

**Comment by FlicAnderson** [comment]
@ewallace what title should I give this section? 'Early Career Co-Supervisor"? "Day-to-Day Supervisor"?  _What am I_:grey_question:

**Comment by FlicAnderson** [comment]
I've written up my intial text for this and am ready to upload it in a branch for review, but I need @swinterbourne to send me another collaboration invite, as my previous one expired. Sorry! :facepalm:

**Comment by ewallace** [comment]
@FlicAnderson I was thinking "Immediate supervisor", likewise "day-to-day supervisor". This paper talks about "novice supervisors" https://www.tandfonline.com/doi/full/10.1080/13562517.2017.1414791 - I don't know if that's appropriate? 

Alternatively, the "Research Associate's Perspective" or "Technician's Perspective" (you aren't exactly a technician) or "Practicing Bioinformatician" or "The Lab Member's perspective as day-to-day supervisor"?

Something?
